### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by stnby** [root4loot/goutils#1]
I would like to use some code of yours. Could you add a license file.

**Comment by root4loot** [comment]
Hi @stnby,

Thank you for your interest and for reaching out regarding the license. I apologize for the delayed response. I've added a [MIT License](../blob/master/LICENSE) file to the repository, so feel free to use the code in your projects!

Contributions are much appreciated. If you have any suggestions, improvements, or features you'd like to see, please don't hesitate to let me know or submit a pull request. 🙂

**Comment by stnby** [comment]
Thank you!
